---

- name: Change root password
  user:
    name: pi
    password: "{{ root_password }}"

- name: Add deployment user
  user:
    name: deploy
    password: "{{ deploy_user_password }}"
    shell: /bin/bash
    append: yes

- name: Add authorized keys for deploy user
  authorized_key:
    user: deploy
    state: present
    manage_dir: yes
    key: "{{ lookup('file', deploy_user_ssh_key_path ) }}"

# Deploy user has passwordless sudo access, because the k3sup tools to create 
# k3s cluster does not support providing a password

- name: Add deploy user to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%deploy ALL='
    line: '%deploy ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s

- name: Disallow password authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify: Restart ssh

- name: Disallow root login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin no"
    state=present
  notify: Restart ssh
