---

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ required_packages }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes