---

- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name: "{{ required_packages }}"

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Change root password
  user: 
    name: pi
    password: "{{ root_password }}"

- name: Add deployment user
  user:
    name: deploy
    password: "{{ deploy_user_password }}"
    shell: /bin/bash
    append: yes

- name: Add authorized keys for deploy user
  authorized_key: 
    user: deploy 
    state: present
    manage_dir: yes
    key: "{{ lookup('file', '/root/pi.pub') }}" # pi.pub is mounted into container

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers
    regexp="deploy ALL"
    line="deploy ALL=(ALL) ALL"
    state=present

- name: Setup ufw
  ufw: state=enabled policy=deny

- name: Allow ssh traffic
  ufw: rule=allow port=22 proto=tcp

- name: Allow http traffic
  ufw: rule=allow port=80 proto=tcp

- name: Allow https traffic
  ufw: rule=allow port=443 proto=tcp

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Disallow root login
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PermitRootLogin"
              line="PermitRootLogin no"
              state=present
  notify: Restart ssh