---

- include: ssh.yml

- name: Common Setup
  hosts: "{{ target }}"
  gather_facts: true
  become: yes
  remote_user: deploy
  roles:
    - role: common
    - role: hostname

- name: k3s Installation
  hosts: "{{ target }}"
  gather_facts: false
  become: yes
  remote_user: deploy
  roles:
    - role: raspbian
    - role: k3s/download
    - role: k3s/node
  vars_prompt:
    - name: hostname
      prompt: Hostname for k3s worker node?
      private: no
