---

- debug:
    var: new_hostname

- debug:
    var: ansible_fqdn

- debug: 
    var: ansible_ssh_host

- name:
  set_fact:
    original: "{{ ansible_fqdn }}"

- name: Change the hostname to our standard
  hostname:
    name: "{{ new_hostname }}"
  when: ansible_fqdn != new_hostname
  register: task_result

- name: restart machine
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  when: task_result is changed

- name: Waiting for server to come back up
  wait_for_connection:
    delay: 10
    connect_timeout: 20
    sleep: 5
    timeout: 300
  when: task_result is changed

- name: Update /etc/hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1\t+raspberrypi'
    line: '127.0.1.1 {{ new_hostname }}'

- name: Validate ansible_fqdn == new_hostname
  assert:
    that:
      ansible_fqdn == new_hostname
