---

- name: Set server IP var
  set_fact:
    server_ip: "{{ groups['master'][0] }}"

- debug:
    var: server_ip

- name: Set agent IPs var
  set_fact:
    nodes: "{{ groups['node'] }}"

- debug:
    var: nodes

- name: Install k3s master
  shell: "k3sup install --ip {{ server_ip }} --user {{ user }} --ssh-key {{ ansible_ssh_private_key_file }}"
  delegate_to: 127.0.0.1

- name: Join nodes
  shell: "k3sup join --ip {{ item }} --server-ip {{ server_ip }} --user {{ user }} --ssh-key {{ ansible_ssh_private_key_file }}"
  with_items: "{{ nodes }}"
  when: len(nodes) > 0
  delegate_to: 127.0.0.1
