---

- name: Base Setup
  hosts: k3s_cluster
  become: yes
  gather_facts: yes
  remote_user: pi
  roles:
    - { role: common, tags: ["common"] }
    - role: users
    - role: firewall
  vars_prompt:
    - name: root_password
      prompt: Enter password for root user?
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
    - name: deploy_user_password
      prompt: Enter password for deployment user?
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7
