---

- name: K3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  remote_user: deploy
  roles:
    - { role: raspbian, tags: ["raspbian"] }
    - { role: k3s/download }


- hosts: master
  remote_user: deploy
  become: yes
  roles:
    - { role: k3s/master, tags: ["k3s-master"] }

- hosts: node
  become: yes
  remote_user: deploy
  roles:
    - { role: k3s/node, tags: ["k3s-node"] }


# - name: K3s exit server
#   hosts: localhost
#   gather_facts: false
#   roles:
#     - { role: exit-server, tags: ["exit-server"] }
#   vars_prompt:
#     - name: do_access_token
#       prompt: Enter Linode access token.
#       private: yes

