---

- name: k3s cluster
  hosts: k3s_cluster
  gather_facts: yes
  become: yes
  remote_user: deploy
  roles:
    - { role: raspbian, tags: ["raspbian"] }
    - { role: k3s, tags: ["k3s"] }
    # - { role: exit-server }

